---
apiVersion: v1
kind: Service
metadata:
  name: php-pvc
  labels:
    name: phppvc
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    env: production
    region: IN
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
  labels:
    name: phppvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:  
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
  labels:
    name: phppvc
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
      region: IN
  template:
    metadata:
      name: php-pod
      labels:
        env: production
        region: IN
    spec:
      containers:
      - name: php-con
        image: php:7.4-apache
        volumeMounts:
        - name: php-vol
          mountPath: /var/www/html/
      volumes:
      - name: php-vol
        persistentVolumeClaim:
          claimName: php-pvc